### ISSUE TITLE
multiple allowbars

### ISSUE THREAD

**Issue by franzenzenhofer** [addyosmani/getUserMedia.js#10]
hi

the repetitive call to navigator.getUserMedia_ just to find out which options syntax it supports is a UX no go, as it leads to multiple "allowbars" in google chrome. 

why is this needed? if you could elaborate i will try to find a solution.

thx and cheers
franz

**Comment by addyosmani** [comment]
The multiple allow bars are actually a bug in Chrome that I've raised with the team here. Effectively, we first check your browser to see if you support gUM and then consume the implementation later on. The issue is that every time you create a new gUM instance where video or audio might be streamed, it'll ask the user for permission. I've told them to try implementing it in such a way that permission is persistently remembered during a session.

If there's a workaround you can think of that would be awesome :)

**Comment by franzenzenhofer** [comment]
pot. workaround i will try out during the weekend
- scrap `optionStyle` functionality completely
- just create both, a `getUserMediaOptionsString` and a `getUserMediaOptionsObject` 
  and then just

``` javascript
try {
 navigator.getUserMedia_(getUserMediaOptionsObject, successCallback, errorCallback);
 }
catch (e) {
 navigator.getUserMedia_(getUserMediaOptionsString, successCallback, errorCallback);
}
```

in my head it works, will report back if there were any real world downsides.
